# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCalculator' do
  # use_frameworks!
pod 'JJMaterialTextField'
pod 'AFViewShaker', '~> 0.0.2'
pod 'MBProgressHUD'

end
